[global]
pid = /Users/acidlake/Development/UPPER/Forge/repos/forge-v3/.forge/services/b4b41168-2d2a-4304-a717-b67b2038f002/php_fpm.pid
error_log = /dev/stderr
[www]
listen = /tmp/fpm_b4b41168.sock
pm = static
pm.max_children = 1
php_admin_value[upload_max_filesize] = 50M
php_admin_value[post_max_size] = 50M
php_admin_value[memory_limit] = 512M
